### ISSUE TITLE
socketio.exceptions.ConnectionError: Connection refused by the server

### ISSUE THREAD

**Issue by Charmve** [1996scarlet/OpenVtuber#6]
```
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "vtuber_link_start.py", line 38, in <module>
    sio.connect("http://192.168.14.131:6789")
  File "/home/charmve/.local/lib/python3.6/site-packages/socketio/client.py", line 282, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
```

`File "vtuber_link_start.py", line 38, in <module>`
`    sio.connect("http://192.168.14.131:6789")`
```
# ======================================================

sio = socketio.Client()

@sio.on('connect', namespace='/kizuna')
def on_connect():
    sio.emit('result_data', 0, namespace='/kizuna')

# sio.connect("http://127.0.0.1:6789")
sio.connect("192.168.14.131:6789")
sio.wait()

# ======================================================
```
the original address is `http://127.0.0.1:6789`,  `192.168.14.131` is my ip.

how to address this error ?

**Comment by Charmve** [comment]
Thanks for guys. This issues is addressed. 

First, RUN the following comment in `NodeServer`.
```
sudo apt remove yarn
sudo apt install curl
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn
```

and then, restart the `python3 vtuber_link_start.py ./res/test/test.mp4 <your-video-path>`.

it WORKS !!!

**Comment by 1996scarlet** [comment]
Thank you for your helpful advice!!!
Your experience will help others configure the environment.
